#define STAR_AMOUNT 1000
#define STAR_START_POS_Z_MAX 20
#define STAR_START_POS_Z_MIN 10
#define STAR_MIN_VELOCITY 1
#define STAR_MAX_VELOCITY 5

#define STAR_TEXTURE_WIDTH 32
#define STAR_TEXTURE_HEIGHT 32

#define SPACE_SIZE 35.0
